version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/srv01
    overwrite: true
permissions:
  - object: /home/ubuntu/srv01
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 30
      runas: ubuntu
  AfterInstall:
    - location: after_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: start.sh
      timeout: 30
      runas: root
  ApplicationStop:
    - location: stop.sh
      timeout: 30
      runas: root