version: 0.2

env:
  variables:
    DOTNET_CLI_HOME: "/tmp/dotnet"
    HOME: "/tmp/home"

phases:
  install:
    runtime-versions:
      dotnet: 6.0
    commands:
      - mkdir -p ${DOTNET_CLI_HOME}
      - mkdir -p ${HOME}
      - export DOTNET_NOLOGO=true
      - export DOTNET_CLI_TELEMETRY_OPTOUT=true

  pre_build:
    commands:
      - echo "Restoring NuGet packages..."
      - dotnet restore --runtime linux-x64

  build:
    commands:
      - echo "Building application..."
      - dotnet build -c Release --no-restore --runtime linux-x64
      - echo "Publishing application..."
      - dotnet publish -c Release --runtime linux-x64

artifacts:
  files:
    - '**/*'
  discard-paths: yes