version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 6.0
  build:
    commands:
      - dotnet publish -c Release --self-contained false --runtime linux-x64 -o ./publish_output
artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - **/*.dll
    - **/*.so
    - **/*.json
  base-directory: 'publish_output'
  discard-paths: no